### ISSUE TITLE
[FEATURE] The `arguments` object is not supported inside functions

### ISSUE THREAD

**Issue by Taritsyn** [koculu/Topaz#11]
Hello, Ahmed!

Currently, inside the functions are not supported the [`arguments`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) object (as in principle and the `this` keyword). For example, now it is impossible to execute such a JS code:

```js
function sum() {
    var result = 0,
        argumentIndex,
        argumentCount = arguments.length
        ;

    for (argumentIndex = 0; argumentIndex < argumentCount; argumentIndex++) {
        result += arguments[argumentIndex];
    }

    return result;
}

sum(120, 5, 18, 63);
```

**Comment by koculu** [comment]
Thank you @Taritsyn for reporting this.
Issue is accepted and I am going to work on this.

**Comment by Taritsyn** [comment]
Thanks for quick response!

**Comment by koculu** [comment]
Hi @Taritsyn 
Arguments object support is made optional and it is disabled by default.
Because it would impact the performance to define a variable on each function call.
It is recommended to use rest parameters instead.

```C#
    /// <summary>
    /// arguments is an Array-like object accessible inside
    /// functions that contains the values of the arguments passed to that function.
    /// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments
    /// Note: In modern code, rest parameters should be preferred.
    /// Default value is false.
    /// </summary>
    public bool DefineSpecialArgumentsObjectOnEachFunctionCall { get; set; }
```

**Comment by Taritsyn** [comment]
Thank you very much!
