### ISSUE TITLE
[Enhancement] .NET Standard 2.1

### ISSUE THREAD

**Issue by edgar-rodrigo-santos** [koculu/Topaz#16]
**What kind of enhancement you would like to have? Please describe.**
The target .NET framework (6 and 7) are not supported in an environment like Unity3D.

**Describe the enhancement you'd like**
Would it be possible to target something like .NET Standard 2.1? This would make it possible to use in Unity3D as well as increase the portability of Topaz. I genuinely don't know if this is a small or a huge effort.

Thank you

**Comment by koculu** [comment]
Added support for net standard 2.1.
I am not going to merge the **net-standard-21** branch to the **main** branch to avoid polluting the main branch with preprocessors.
It would be nice if you provide a feedback on the net standard build.

You can find the package at: 
https://www.nuget.org/packages/Topaz/

**Comment by edgar-rodrigo-santos** [comment]
Hi,

I just wanted to give you some feedback on the more complex tests.
If we use coroutines in Unity code and use AOT compilation, Topaz doesn't work.

We did some testing with Mono (JIT) and it works but it doesn't with IL2CPP (which is a requirement to do UWP builds and therefore a dealbreaker for our scenarios).

**Comment by koculu** [comment]
Hi @edgar-rodrigo-santos 
Have you figured out which part of the Topaz code blocks AOT?
If the reflection is a block in your case, the reflection usage can be disabled by using custom interfaces.
If you find other parts that are need to be disabled we can implement additional extension interfaces to unblock AOT usage.

**Comment by edgar-rodrigo-santos** [comment]
Thanks for the reply.

No, we didn't get into exploring Topaz itself internally. 
We actually opened a bug report in Unity (we thought it was acceptable to expect some parity between Mono and IL2CPP backends) and they answered back: "This is because it relies on dynamic C# features". 
We then realized that it makes sense because IL2CPP is AOT.

Regarding unblocking AOT usage, if you think this could be done somehow, we would definitely be interested and also open to whatever pointers you could provide.

**Comment by koculu** [comment]
I have tested Topaz using dotnet AOT compilation feature and it works out of the box.
I have no idea for Unity IL2CPP side.
Could you please provide the bug report details or link to the bug report?
Do you get a compilation error or runtime error?

Depending on the answer providing custom `DefaultObjectProxy `and `DelegateInvoker `using `TopazEngineSetup `might help.

In this case you have to write your own `IObjectProxy `and `IDelegateInvoker `implementations without using dynamic features. (Reflection)

If it is a compilation error you can consider removing the source files that use dynamic features and provide your custom implementation without using dynamic features.

Provide options using following class:
https://github.com/koculu/Topaz/blob/main/src/Topaz/TopazEngineSetup.cs

**Comment by edgar-rodrigo-santos** [comment]
Thank you for your reply.

Unfortunately, the issue never made it to the public tracker (only exchanged some messages with unity support) but I will write it here (I just realized I never provided specific details of what happens).

(original ticket:)
1. What happened
I'm using a JavaScript interpreter library to run a javascript script at runtime.
If a C# co-routine function called from the javascript script "yields" (in any way or shape) the app crashes.
This doesn't happen (and the app works flawlessly) if we use Mono instead of IL2CPP.
While I reproduced this on a PC app, this is a blocker for us because we target Hololens2 in which we only have IL2CPP.

2. How can we reproduce it using the example you attached
The attached project was made specifically to reproduce the issue.
The build target is PC to make it more practical to use.
If Mono is used, the app runs perfectly until the end.
If IL2CPP is used, the app crashes as soon as a coroutine in C# "yields" (in this scenario, "yield return WaitForSeconds")

So, the error is at runtime and only manifests when we yield a coroutine in the Unity side. I tried many ways to go around this, including not using unity coroutines and using specific C# instructions (e.g. Task.Yield, async/awaits, etc) without success.

The C# code running on Unity: 
https://github.com/kit-ar/bug.TopazIL2CPP/blob/master/IL2CPP_bug/Assets/Test/TestScript.cs
The JS code running through Topaz: 
https://github.com/kit-ar/bug.TopazIL2CPP/blob/master/IL2CPP_bug/Assets/Test/Resources/jsTest.txt

Are you sure it works ok with coroutines using AOT compilation? I am asking because my "Hello world" testing went well but a scenario with my own coroutines yielding did not.

**Comment by koculu** [comment]
Hi @edgar-rodrigo-santos 
The following PR adds an interface to customize the await behavior.
IL2CPP does not support await on dynamic casts.
In order to avoid dynamic casts you have to implement your own await handler without using the dynamic keyword.
The custom await handler is required because there is no way to write a single await handler that supports all possible generic Tasks.

https://github.com/koculu/Topaz/pull/27
netstandard2.1 release version: [1.3.8.9](https://www.nuget.org/packages/Topaz/1.3.8.9)
