### ISSUE TITLE
How i can pass delegate to SetValue?

### ISSUE THREAD

**Issue by perdub** [koculu/Topaz#17]
In Jint i can make something like this:
```
_engine.SetValue("print", (text)=>{Console.WriteLine(text);});
```

Is there any way to make something like this in Topaz? I get a `Tenray.Topaz.TopazException: Constructor call on null is not defined.` when i try to pass a delegate to `engine.SetValue()`

**Comment by koculu** [comment]
The following code works fine. Could you share the exact code that you get the exception?
```cs
    public void TestLambdaFunction()
    {
        var engine = new TopazEngine();
        engine.SetValue("print", (string text) => { Console.WriteLine(text); });
        engine.ExecuteExpression("print('text')");
    }
````

**Comment by perdub** [comment]
I get exception when i try to use `engine.SetValue("print", (text)=>{Console.WriteLine(text);});`, but its work when i mark types explicit like in your explame `(string text)=>{Console.WrtieLine(text);}`, thanks you for the help!
