### ISSUE TITLE
Concurrent Execution Question

### ISSUE THREAD

**Issue by blakepell** [koculu/Topaz#28]
First of all, thank you for sharing your project!

Preface: I'm probably doing something wrong.

In regards to concurrent execution, I've tried this out in a game client I'm writing where a Topaz script is executed as a command in a client WPF application.  It works, there's no blocking on the UI and the scripts are running.  But, if I execute two commands concurrently, the first topaz script stops execution when the 2nd is run, and then when the 2nd is over it picks up on the 1st one again where it stopped.  I might expect that if I used the same `TopazEngine` object but I created a new one with each execution (thinking they would be independent of each other).  The script below counts from 0 to 9 with a 1 second pause each loop.

```csharp
  public override void Execute()
  {
      var engine = new TopazEngine();
      engine.AddType(typeof(TerminalScriptCommands), "Terminal");
      engine.ExecuteScript(@"
      for (var i = 0; i < 10; i++)
      {
          Terminal.Send(""say "" + i)
          await Terminal.Pause(1000)
      }");
  }
```

Is it possible for two TopazEngine executes to run at the same time without one halting execution of the other?

I'll include the `Pause` function also in case anything it's doing might be a contributing factor (this pause function is one I've used with Moonsharp Lua/NLua in the past).

``` csharp
  public static void Pause(int milliseconds)
  {
      DispatcherFrame df = new DispatcherFrame();
  
      new Thread(() =>
      {
          Thread.Sleep(TimeSpan.FromMilliseconds(milliseconds));
          df.Continue = false;
  
      }).Start();
  
      Dispatcher.PushFrame(df);
  }
```

**Comment by koculu** [comment]
Thank you, @blakepell .

Topaz supports multi-threading and you can run scripts in parallel using the same Topaz script engine. There are already running unit tests to ensure that parallel script execution is fine.

**One think that catch my eyes:**
You are using an await statement  in your JavaScript code but you are not using Topaz Engine **ExecuteScriptAsync** function. If you do that, your await statement would turn into a **Task.Wait()** statement and that would block the caller.

**If above hint does not help:**
Could you please share a working console application that demonstrates the issue?
There might be something wrong in other places in the code but I am out of ideas at the moment.

**Comment by blakepell** [comment]
Would a bare bones WPF app work?

- https://github.com/blakepell/TopazTest

There is a button click event in `MainWindow.xaml.cs` that runs a Topaz script (that script loops 10 times and echos out a message each loop).  If I click the button again while the 1st script is running (new TopazEngine instance) the 1st script stops executing, the 2nd script starts executing and then when the 2nd script is done the 1st one picks up where it left off and finishes.

I tried different variations including the async suggestions.

``` csharp
  private async void ButtonRunScript_Click(object sender, RoutedEventArgs e)
  {
      var engine = new TopazEngine();
      engine.AddType(typeof(TerminalScriptCommands), "Terminal");
      await engine.ExecuteScriptAsync(@"
      for (var i = 0; i < 10; i++)
      {
          Terminal.Echo(""say "" + i)
          await Terminal.Pause(1000)
      }");
  }
```

For context, the pause is there because in the text based game client a player might need to control the timing of sending commands to the game.

**Comment by koculu** [comment]
The **Terminal.Pause** method returns nothing and it is not awaitable.
You can only await Tasks or ValueTasks.

I have updated the code as following and it works as expected.
```cs
        public static void Echo(string? text)
        {
            Window.TextOutput.AppendText($"{text}\r\n");
        }

        public static async Task Pause(int milliseconds)
        {
            await Task.Delay(milliseconds).ConfigureAwait(true);
        }
```

**Comment by blakepell** [comment]
Good call, and thank you again!  After your change it works as expected.
