### ISSUE TITLE
Why not using Esprima from nuget

### ISSUE THREAD

**Issue by MarioGK** [koculu/topaz#4]
Hi, thanks for the amazing project it looks amazing, and probably it will suit me needs perfectly.

I was just wondering why use a "hard copy" of Esprima instead of using the Nuget version which is more up to date (for example it got updated just yesterday).

Again thanks for the project, will try my best to help you if i find something that needs fixing/improvement.

**Comment by koculu** [comment]
Hi Mario,
I made a minor change in Esprima to improve execution performance (not parser performance but runtime performance). Parse logic is untouched. Overwrite it with latest Esprima via a basic copy operation and merge.

**Comment by koculu** [comment]
The second important fact is:
Esprima is under heavy development. I struggled with a faulty release once. Then I decided to take a snapshot.
Therefore I could stabilize Topaz by excluding 3rd party effects.
